### ISSUE TITLE
G111 Main Readme Edit

### ISSUE THREAD

**Issue by juke-cappatalist** [Zengit123/G-standards#1]
Some edits to the G1111 main readme file
[Tanks-readme.txt](https://github.com/Zengit123/G-standards/files/6534085/Tanks-readme.txt)

**Comment by Zengit123** [comment]
Thank you for your help.
Your comments have been included in the description of G111.
You wrote G1111, but that is the (Tanks) branch. I can see you wanted to propose changes to G111(Combat vehicles) by the way the texts are similar.
The way "readme's" work is they describe the branch(folder) they are in. So if a "readme.md" is in the folder "G111(Combat vehicles)", it describes that folder.
